export interface IndustryConfig {
  id: string;
  label: string;
  emoji: string;
  businessType: string; // "practice" | "firm" | "company" | "clinic" etc
  exampleBusiness: string;
  exampleCity: string;
  exampleState: string;
  exampleWebsite: string;
  competitors: { name: string; baseScore: number }[];
  queries: { text: string; category: string }[];
  reportHighlight: string;
  nextSteps: string[];
}

export const INDUSTRIES: IndustryConfig[] = [
  {
    id: "dental",
    label: "Dental Clinics",
    emoji: "🦷",
    businessType: "practice",
    exampleBusiness: "Riverside Dental",
    exampleCity: "Austin",
    exampleState: "TX",
    exampleWebsite: "riversidedental.com",
    competitors: [
      { name: "BrightSmile Dental", baseScore: 78 },
      { name: "Lakeside Family Dental", baseScore: 64 },
      { name: "Summit Dental Group", baseScore: 58 },
      { name: "Austin Premier Dentistry", baseScore: 52 },
    ],
    queries: [
      { text: "Best dentist in Austin for dental implants", category: "implants" },
      { text: "Top-rated dentist near me for teeth whitening", category: "cosmetic" },
      { text: "Best family dentist in Austin TX", category: "general" },
      { text: "Affordable dental implants Austin", category: "implants" },
      { text: "Who is the best cosmetic dentist in Austin?", category: "cosmetic" },
      { text: "Best dentist for emergency tooth extraction Austin", category: "emergency" },
      { text: "Top dentist for Invisalign in Austin", category: "orthodontics" },
      { text: "Best pediatric dentist in Austin", category: "pediatric" },
      { text: "Which dentist in Austin accepts Delta Dental?", category: "insurance" },
      { text: "Best dentist for crowns and bridges in Austin", category: "restorative" },
      { text: "Highest rated dental clinic in Austin Texas", category: "general" },
      { text: "Best dentist for root canal in Austin", category: "restorative" },
      { text: "Top reviewed dentist in downtown Austin", category: "general" },
      { text: "Best dentist for veneers in Austin", category: "cosmetic" },
      { text: "Which Austin dentist is best for anxious patients?", category: "general" },
      { text: "Best same-day dentist appointment Austin", category: "emergency" },
      { text: "Best dentist for gum disease treatment Austin", category: "restorative" },
      { text: "Top dentist for dentures in Austin TX", category: "restorative" },
      { text: "Best dentist accepting new patients in Austin", category: "general" },
      { text: "Which dental clinic in Austin has the best reviews?", category: "general" },
      { text: "Best dentist for sleep apnea mouthguard Austin", category: "specialty" },
      { text: "Top dental implant specialist in Austin Texas", category: "implants" },
      { text: "Best dentist for TMJ treatment in Austin", category: "specialty" },
      { text: "Which Austin dentist offers payment plans?", category: "insurance" },
      { text: "Best full-mouth dental implants Austin", category: "implants" },
      { text: "Best dentist for teeth cleaning in Austin", category: "general" },
      { text: "Top-rated dentist in South Austin", category: "general" },
      { text: "Best dentist for wisdom teeth removal Austin", category: "restorative" },
      { text: "Which dentist in Austin is best for seniors?", category: "general" },
      { text: "Best dentist for dental bonding in Austin", category: "cosmetic" },
    ],
    reportHighlight: "Implant-related queries showed the most growth — from 5 mentions last month to 17 this month.",
    nextSteps: [
      "Improve implant service page content with patient-focused FAQs",
      "Strengthen local authority through 2 relevant publication opportunities",
      "Fix 3 directory listing inconsistencies (NAP mismatch on Yelp, Healthgrades)",
      "Add structured data to doctor/team pages",
      "Improve emergency dentistry content for after-hours queries",
    ],
  },
  {
    id: "legal",
    label: "Law Firms",
    emoji: "⚖️",
    businessType: "firm",
    exampleBusiness: "Sterling & Reed Law",
    exampleCity: "Miami",
    exampleState: "FL",
    exampleWebsite: "sterlingreedlaw.com",
    competitors: [
      { name: "Morgan Legal Group", baseScore: 81 },
      { name: "Coastline Law Partners", baseScore: 67 },
      { name: "Pinnacle Injury Lawyers", baseScore: 55 },
      { name: "First Coast Legal", baseScore: 48 },
    ],
    queries: [
      { text: "Best personal injury lawyer in Miami", category: "personal injury" },
      { text: "Top-rated attorney near me for car accident cases", category: "personal injury" },
      { text: "Best family law attorney in Miami FL", category: "family law" },
      { text: "Affordable criminal defense lawyer Miami", category: "criminal defense" },
      { text: "Who is the best divorce attorney in Miami?", category: "family law" },
      { text: "Best lawyer for slip and fall in Miami", category: "personal injury" },
      { text: "Top estate planning attorney in Miami", category: "estate planning" },
      { text: "Best immigration lawyer in Miami", category: "immigration" },
      { text: "Which law firm in Miami handles wrongful death?", category: "personal injury" },
      { text: "Best business litigation attorney in Miami", category: "business law" },
      { text: "Highest rated law firm in Miami Florida", category: "general" },
      { text: "Best lawyer for medical malpractice in Miami", category: "personal injury" },
      { text: "Top reviewed attorney in downtown Miami", category: "general" },
      { text: "Best real estate lawyer in Miami", category: "real estate law" },
      { text: "Which Miami attorney is best for DUI defense?", category: "criminal defense" },
      { text: "Best contingency fee lawyer Miami", category: "personal injury" },
      { text: "Best lawyer for child custody in Miami", category: "family law" },
      { text: "Top trademark attorney in Miami FL", category: "business law" },
      { text: "Best law firm accepting new clients in Miami", category: "general" },
      { text: "Which law firm in Miami has the best reviews?", category: "general" },
      { text: "Best workers compensation lawyer Miami", category: "personal injury" },
      { text: "Top bankruptcy attorney in Miami Florida", category: "bankruptcy" },
      { text: "Best lawyer for contract disputes in Miami", category: "business law" },
      { text: "Which Miami law firm offers free consultations?", category: "general" },
      { text: "Best class action attorney Miami", category: "personal injury" },
      { text: "Best lawyer for wills and trusts in Miami", category: "estate planning" },
      { text: "Top-rated law firm in Brickell Miami", category: "general" },
      { text: "Best lawyer for truck accident in Miami", category: "personal injury" },
      { text: "Which attorney in Miami is best for startups?", category: "business law" },
      { text: "Best tax law attorney in Miami", category: "tax law" },
    ],
    reportHighlight: "Personal injury queries grew from 8 mentions to 21 mentions, driven by improved case result pages.",
    nextSteps: [
      "Publish 3 case result summaries for high-value personal injury wins",
      "Improve attorney bio pages with credentials and bar associations",
      "Add FAQ schema to practice area pages",
      "Fix inconsistent NAP across Avvo, Martindale, and FindLaw",
      "Strengthen Google Business Profile with weekly posts",
    ],
  },
  {
    id: "medical",
    label: "Medical Clinics",
    emoji: "🏥",
    businessType: "clinic",
    exampleBusiness: "Cedar Park Medical",
    exampleCity: "Denver",
    exampleState: "CO",
    exampleWebsite: "cedarparkmedical.com",
    competitors: [
      { name: "Rocky Mountain Health", baseScore: 76 },
      { name: "Front Range Clinic", baseScore: 61 },
      { name: "Mile High Medical", baseScore: 54 },
      { name: "Peak Wellness Clinic", baseScore: 46 },
    ],
    queries: [
      { text: "Best primary care doctor in Denver", category: "primary care" },
      { text: "Top-rated medical clinic near me", category: "general" },
      { text: "Best walk-in clinic in Denver CO", category: "urgent care" },
      { text: "Best internal medicine doctor Denver", category: "primary care" },
      { text: "Who is the best family doctor in Denver?", category: "primary care" },
      { text: "Best urgent care clinic in Denver for same-day", category: "urgent care" },
      { text: "Top preventive care clinic in Denver", category: "preventive" },
      { text: "Best clinic for annual physical in Denver", category: "preventive" },
      { text: "Which medical clinic in Denver accepts Blue Cross?", category: "insurance" },
      { text: "Best clinic for chronic disease management Denver", category: "chronic care" },
      { text: "Highest rated medical center in Denver Colorado", category: "general" },
      { text: "Best clinic for diabetes management in Denver", category: "chronic care" },
      { text: "Top reviewed medical clinic in downtown Denver", category: "general" },
      { text: "Best women's health clinic in Denver", category: "specialty" },
      { text: "Which Denver clinic is best for telemedicine?", category: "general" },
      { text: "Best clinic for blood work in Denver", category: "diagnostics" },
      { text: "Best heart doctor in Denver", category: "cardiology" },
      { text: "Top dermatology clinic in Denver CO", category: "dermatology" },
      { text: "Best medical clinic accepting new patients Denver", category: "general" },
      { text: "Which medical clinic in Denver has the best reviews?", category: "general" },
      { text: "Best clinic for hypertension management Denver", category: "chronic care" },
      { text: "Top rated internist in Denver Colorado", category: "primary care" },
      { text: "Best clinic for allergy testing in Denver", category: "specialty" },
      { text: "Which Denver clinic offers weekend appointments?", category: "general" },
      { text: "Best occupational health clinic Denver", category: "specialty" },
      { text: "Best clinic for flu shots in Denver", category: "preventive" },
      { text: "Top-rated medical clinic in Aurora CO", category: "general" },
      { text: "Best clinic for weight management in Denver", category: "specialty" },
      { text: "Which medical clinic in Denver is best for seniors?", category: "primary care" },
      { text: "Best mental health clinic in Denver", category: "behavioral health" },
    ],
    reportHighlight: "Primary care queries improved from 12 to 24 mentions after adding physician credential pages.",
    nextSteps: [
      "Create detailed physician credential pages with board certifications",
      "Add insurance-accepted information to each service page",
      "Improve telemedicine landing page with clear booking instructions",
      "Fix inconsistent listing data across Healthgrades and WebMD",
      "Add patient education content for top chronic conditions",
    ],
  },
  {
    id: "medspa",
    label: "Med Spas",
    emoji: "💆",
    businessType: "spa",
    exampleBusiness: "Glow Aesthetics",
    exampleCity: "Scottsdale",
    exampleState: "AZ",
    exampleWebsite: "glowaesthetics.com",
    competitors: [
      { name: "Radiance MedSpa", baseScore: 79 },
      { name: "Desert Bloom Aesthetics", baseScore: 66 },
      { name: "Luxe Skin & Body", baseScore: 57 },
      { name: "Scottsdale Beauty Bar", baseScore: 49 },
    ],
    queries: [
      { text: "Best med spa in Scottsdale for Botox", category: "injectables" },
      { text: "Top-rated medical spa near me for facials", category: "skincare" },
      { text: "Best med spa in Scottsdale AZ", category: "general" },
      { text: "Affordable Botox treatments Scottsdale", category: "injectables" },
      { text: "Who is the best aesthetic provider in Scottsdale?", category: "general" },
      { text: "Best med spa for laser hair removal Scottsdale", category: "laser" },
      { text: "Top med spa for chemical peels in Scottsdale", category: "skincare" },
      { text: "Best med spa for microneedling in Scottsdale", category: "skincare" },
      { text: "Which med spa in Scottsdale offers CoolSculpting?", category: "body" },
      { text: "Best med spa for dermal fillers in Scottsdale", category: "injectables" },
      { text: "Highest rated medical spa in Scottsdale Arizona", category: "general" },
      { text: "Best med spa for laser skin resurfacing Scottsdale", category: "laser" },
      { text: "Top reviewed med spa in Old Town Scottsdale", category: "general" },
      { text: "Best med spa for lip filler in Scottsdale", category: "injectables" },
      { text: "Which Scottsdale med spa is best for anti-aging?", category: "skincare" },
      { text: "Best med spa for IV therapy in Scottsdale", category: "wellness" },
      { text: "Best med spa for body contouring Scottsdale", category: "body" },
      { text: "Top medical spa for PRP facials in Scottsdale", category: "skincare" },
      { text: "Best med spa accepting new clients in Scottsdale", category: "general" },
      { text: "Which med spa in Scottsdale has the best reviews?", category: "general" },
      { text: "Best med spa for hormone therapy Scottsdale", category: "wellness" },
      { text: "Top aesthetic clinic in Scottsdale Arizona", category: "general" },
      { text: "Best med spa for Kybella in Scottsdale", category: "injectables" },
      { text: "Which Scottsdale med spa offers membership programs?", category: "general" },
      { text: "Best medical spa for Morpheus8 Scottsdale", category: "laser" },
      { text: "Best med spa for hydrafacials in Scottsdale", category: "skincare" },
      { text: "Top-rated med spa in North Scottsdale", category: "general" },
      { text: "Best med spa for weight loss programs Scottsdale", category: "wellness" },
      { text: "Which med spa in Scottsdale is best for men?", category: "general" },
      { text: "Best med spa for IPL treatments in Scottsdale", category: "laser" },
    ],
    reportHighlight: "Injectable queries surged from 6 to 19 mentions after publishing before/after treatment galleries.",
    nextSteps: [
      "Publish before/after treatment galleries for top procedures",
      "Add provider credential pages with training and certifications",
      "Create treatment comparison content (Botox vs Dysport, etc.)",
      "Improve Google Business Profile with service menu and photos",
      "Build content around seasonal treatment trends",
    ],
  },
  {
    id: "hvac",
    label: "HVAC Companies",
    emoji: "🏠",
    businessType: "company",
    exampleBusiness: "Reliable Air & Heat",
    exampleCity: "Phoenix",
    exampleState: "AZ",
    exampleWebsite: "reliableairphx.com",
    competitors: [
      { name: "Valley Comfort HVAC", baseScore: 77 },
      { name: "Desert Cool Air", baseScore: 63 },
      { name: "Premier Air Conditioning", baseScore: 56 },
      { name: "Phoenix Heating Pros", baseScore: 47 },
    ],
    queries: [
      { text: "Best HVAC company in Phoenix", category: "general" },
      { text: "Top-rated AC repair near me", category: "repair" },
      { text: "Best HVAC company in Phoenix AZ", category: "general" },
      { text: "Affordable air conditioning repair Phoenix", category: "repair" },
      { text: "Who is the best HVAC contractor in Phoenix?", category: "general" },
      { text: "Best HVAC company for emergency AC repair Phoenix", category: "emergency" },
      { text: "Top HVAC company for AC installation in Phoenix", category: "installation" },
      { text: "Best furnace repair company in Phoenix", category: "repair" },
      { text: "Which HVAC company in Phoenix accepts financing?", category: "financing" },
      { text: "Best HVAC company for duct cleaning in Phoenix", category: "maintenance" },
      { text: "Highest rated HVAC contractor in Phoenix Arizona", category: "general" },
      { text: "Best HVAC company for AC replacement Phoenix", category: "installation" },
      { text: "Top reviewed HVAC company in Phoenix", category: "general" },
      { text: "Best HVAC company for mini-split installation Phoenix", category: "installation" },
      { text: "Which Phoenix HVAC company is best for maintenance plans?", category: "maintenance" },
      { text: "Best 24/7 HVAC service Phoenix", category: "emergency" },
      { text: "Best HVAC company for thermostat installation Phoenix", category: "installation" },
      { text: "Top HVAC company for indoor air quality Phoenix", category: "specialty" },
      { text: "Best HVAC company accepting new customers in Phoenix", category: "general" },
      { text: "Which HVAC company in Phoenix has the best reviews?", category: "general" },
      { text: "Best HVAC company for heat pump repair Phoenix", category: "repair" },
      { text: "Top air conditioning service in Phoenix Arizona", category: "general" },
      { text: "Best HVAC company for ductless AC Phoenix", category: "installation" },
      { text: "Which Phoenix HVAC company offers free estimates?", category: "general" },
      { text: "Best HVAC company for seasonal tune-up Phoenix", category: "maintenance" },
      { text: "Best HVAC company for evaporative cooler service Phoenix", category: "maintenance" },
      { text: "Top-rated HVAC company in Tempe AZ", category: "general" },
      { text: "Best HVAC company for commercial AC Phoenix", category: "commercial" },
      { text: "Which HVAC company in Phoenix is best for new construction?", category: "installation" },
      { text: "Best HVAC company for AC warranty service Phoenix", category: "repair" },
    ],
    reportHighlight: "AC repair queries climbed from 9 to 22 mentions after adding emergency service content.",
    nextSteps: [
      "Create dedicated emergency AC repair landing page",
      "Add financing options page with clear terms",
      "Improve service area pages with city-specific content",
      "Fix inconsistent business listings across directories",
      "Publish seasonal maintenance tips content",
    ],
  },
  {
    id: "plumbing",
    label: "Plumbers",
    emoji: "🔧",
    businessType: "company",
    exampleBusiness: "Express Plumbing Co",
    exampleCity: "Dallas",
    exampleState: "TX",
    exampleWebsite: "expressplumbingdallas.com",
    competitors: [
      { name: "Citywide Plumbing", baseScore: 75 },
      { name: "Reliable Pipe Pros", baseScore: 62 },
      { name: "Dallas Drain Experts", baseScore: 55 },
      { name: "Lone Star Plumbing", baseScore: 48 },
    ],
    queries: [
      { text: "Best plumber in Dallas", category: "general" },
      { text: "Top-rated plumber near me for emergency repairs", category: "emergency" },
      { text: "Best plumbing company in Dallas TX", category: "general" },
      { text: "Affordable drain cleaning Dallas", category: "drain" },
      { text: "Who is the best plumber in Dallas?", category: "general" },
      { text: "Best plumber for emergency pipe burst Dallas", category: "emergency" },
      { text: "Top plumber for water heater installation in Dallas", category: "water heater" },
      { text: "Best plumber for slab leak repair in Dallas", category: "leak" },
      { text: "Which plumber in Dallas offers 24/7 service?", category: "emergency" },
      { text: "Best plumber for sewer line repair in Dallas", category: "sewer" },
      { text: "Highest rated plumbing company in Dallas Texas", category: "general" },
      { text: "Best plumber for tankless water heater Dallas", category: "water heater" },
      { text: "Top reviewed plumber in Dallas", category: "general" },
      { text: "Best plumber for garbage disposal repair Dallas", category: "repair" },
      { text: "Which Dallas plumber is best for bathroom remodels?", category: "remodel" },
      { text: "Best plumber for hydro jetting in Dallas", category: "drain" },
      { text: "Best plumber for gas line repair Dallas", category: "specialty" },
      { text: "Top plumber for sump pump installation Dallas", category: "specialty" },
      { text: "Best plumber accepting new customers in Dallas", category: "general" },
      { text: "Which plumber in Dallas has the best reviews?", category: "general" },
      { text: "Best plumber for leak detection in Dallas", category: "leak" },
      { text: "Top plumbing service in Dallas Texas", category: "general" },
      { text: "Best plumber for backflow testing Dallas", category: "specialty" },
      { text: "Which Dallas plumber offers free estimates?", category: "general" },
      { text: "Best plumber for kitchen plumbing Dallas", category: "repair" },
      { text: "Best plumber for repiping in Dallas TX", category: "remodel" },
      { text: "Top-rated plumber in Plano TX", category: "general" },
      { text: "Best plumber for commercial plumbing Dallas", category: "commercial" },
      { text: "Which plumber in Dallas is best for water filtration?", category: "specialty" },
      { text: "Best plumber for faucet and fixture installation Dallas", category: "repair" },
    ],
    reportHighlight: "Emergency plumbing queries rose from 7 to 18 mentions after creating a 24/7 service landing page.",
    nextSteps: [
      "Create 24/7 emergency service landing page with clear call-to-action",
      "Add water heater comparison guide (tank vs tankless)",
      "Improve service area pages with neighborhood-specific content",
      "Fix NAP inconsistencies across Angi, HomeAdvisor, and Yelp",
      "Publish drain maintenance prevention content for homeowners",
    ],
  },
  {
    id: "roofing",
    label: "Roofers",
    emoji: "🏗️",
    businessType: "company",
    exampleBusiness: "Summit Roofing",
    exampleCity: "Nashville",
    exampleState: "TN",
    exampleWebsite: "summitroofingnashville.com",
    competitors: [
      { name: "Music City Roofing", baseScore: 76 },
      { name: "TopTier Roofers", baseScore: 63 },
      { name: "Nashville Roof Co", baseScore: 54 },
      { name: "Volunteer Roofing", baseScore: 45 },
    ],
    queries: [
      { text: "Best roofing company in Nashville", category: "general" },
      { text: "Top-rated roofer near me for roof repair", category: "repair" },
      { text: "Best roofing contractor in Nashville TN", category: "general" },
      { text: "Affordable roof replacement Nashville", category: "replacement" },
      { text: "Who is the best roofer in Nashville?", category: "general" },
      { text: "Best roofer for emergency roof leak Nashville", category: "emergency" },
      { text: "Top roofing company for new roof installation Nashville", category: "installation" },
      { text: "Best roofer for storm damage repair in Nashville", category: "storm" },
      { text: "Which roofer in Nashville offers free inspections?", category: "general" },
      { text: "Best roofing company for gutter installation Nashville", category: "gutters" },
      { text: "Highest rated roofing contractor in Nashville Tennessee", category: "general" },
      { text: "Best roofer for metal roofing in Nashville", category: "materials" },
      { text: "Top reviewed roofing company in Nashville", category: "general" },
      { text: "Best roofer for shingle replacement Nashville", category: "repair" },
      { text: "Which Nashville roofer is best for flat roofs?", category: "specialty" },
      { text: "Best roofing company for insurance claims Nashville", category: "insurance" },
      { text: "Best roofer for skylight installation Nashville", category: "specialty" },
      { text: "Top roofing company for commercial roofs Nashville", category: "commercial" },
      { text: "Best roofer accepting new projects in Nashville", category: "general" },
      { text: "Which roofing company in Nashville has the best reviews?", category: "general" },
      { text: "Best roofer for roof inspection in Nashville", category: "inspection" },
      { text: "Top roofing service in Nashville Tennessee", category: "general" },
      { text: "Best roofer for tile roof repair Nashville", category: "repair" },
      { text: "Which Nashville roofer offers financing?", category: "general" },
      { text: "Best roofing company for ventilation Nashville", category: "specialty" },
      { text: "Best roofer for chimney flashing Nashville", category: "repair" },
      { text: "Top-rated roofer in Franklin TN", category: "general" },
      { text: "Best roofer for slate roofing in Nashville", category: "materials" },
      { text: "Which roofer in Nashville is best for historic homes?", category: "specialty" },
      { text: "Best roofing company for roof maintenance Nashville", category: "maintenance" },
    ],
    reportHighlight: "Storm damage repair queries grew from 4 to 15 mentions after publishing hail damage resource content.",
    nextSteps: [
      "Create storm damage resource center with Nashville-specific weather data",
      "Add roofing material comparison guide (asphalt vs metal vs tile)",
      "Publish insurance claim walkthrough content",
      "Improve Google Business Profile photos of completed projects",
      "Fix inconsistent business data across roofing directories",
    ],
  },
  {
    id: "hotels",
    label: "Hotels",
    emoji: "🏨",
    businessType: "hotel",
    exampleBusiness: "The Briarwood Inn",
    exampleCity: "Asheville",
    exampleState: "NC",
    exampleWebsite: "briarwoodinn.com",
    competitors: [
      { name: "Grand Mountain Lodge", baseScore: 80 },
      { name: "Blue Ridge Boutique Hotel", baseScore: 68 },
      { name: "Asheville Grand Hotel", baseScore: 58 },
      { name: "Summit Springs Inn", baseScore: 50 },
    ],
    queries: [
      { text: "Best hotel in Asheville", category: "general" },
      { text: "Top-rated boutique hotel near me in Asheville", category: "boutique" },
      { text: "Best hotel in Asheville NC for couples", category: "romantic" },
      { text: "Best pet-friendly hotel in Asheville", category: "pet-friendly" },
      { text: "Who has the best hotel in downtown Asheville?", category: "location" },
      { text: "Best hotel in Asheville with mountain views", category: "amenities" },
      { text: "Top hotel for weekend getaway in Asheville", category: "general" },
      { text: "Best luxury hotel in Asheville", category: "luxury" },
      { text: "Which hotel in Asheville has the best breakfast?", category: "amenities" },
      { text: "Best hotel in Asheville near Biltmore", category: "location" },
      { text: "Highest rated hotel in Asheville North Carolina", category: "general" },
      { text: "Best hotel with pool in Asheville", category: "amenities" },
      { text: "Top reviewed hotel in Asheville", category: "general" },
      { text: "Best hotel in Asheville for families", category: "family" },
      { text: "Which Asheville hotel is best for a honeymoon?", category: "romantic" },
      { text: "Best hotel in Asheville with free parking", category: "amenities" },
      { text: "Best bed and breakfast in Asheville", category: "boutique" },
      { text: "Top hotel in Asheville with spa services", category: "amenities" },
      { text: "Best hotel in Asheville walking distance to downtown", category: "location" },
      { text: "Which hotel in Asheville has the best reviews?", category: "general" },
      { text: "Best hotel in Asheville for business travelers", category: "business" },
      { text: "Top rated inn in Asheville North Carolina", category: "boutique" },
      { text: "Best hotel in Asheville with fireplace in room", category: "amenities" },
      { text: "Which Asheville hotel offers the best value?", category: "general" },
      { text: "Best hotel in Asheville for fall foliage", category: "seasonal" },
      { text: "Best hotel in Asheville with restaurant on-site", category: "amenities" },
      { text: "Top-rated hotel in Biltmore Village", category: "location" },
      { text: "Best hotel in Asheville for solo travelers", category: "general" },
      { text: "Which hotel in Asheville is best for weddings?", category: "events" },
      { text: "Best hotel in Asheville with outdoor terrace", category: "amenities" },
    ],
    reportHighlight: "Romantic getaway queries increased from 8 to 20 mentions after adding curated couples' experience content.",
    nextSteps: [
      "Create curated experience packages (romantic, family, adventure)",
      "Add neighborhood guide content for Asheville attractions",
      "Improve amenity pages with rich photos and descriptions",
      "Strengthen presence on OTAs with consistent descriptions",
      "Publish seasonal content tied to local events and attractions",
    ],
  },
  {
    id: "restaurants",
    label: "Restaurants",
    emoji: "🍽️",
    businessType: "restaurant",
    exampleBusiness: "Olive & Ember",
    exampleCity: "Portland",
    exampleState: "OR",
    exampleWebsite: "oliveandember.com",
    competitors: [
      { name: "The Wild Thistle", baseScore: 82 },
      { name: "Harbor Light Kitchen", baseScore: 69 },
      { name: "Stumptown Table", baseScore: 58 },
      { name: "Riverbend Bistro", baseScore: 51 },
    ],
    queries: [
      { text: "Best restaurant in Portland", category: "general" },
      { text: "Top-rated restaurant near me in Portland", category: "general" },
      { text: "Best fine dining restaurant in Portland OR", category: "fine dining" },
      { text: "Best brunch spot in Portland", category: "brunch" },
      { text: "Who has the best dinner in Portland?", category: "general" },
      { text: "Best restaurant in Portland for date night", category: "romantic" },
      { text: "Top restaurant for outdoor dining in Portland", category: "outdoor" },
      { text: "Best farm-to-table restaurant in Portland", category: "specialty" },
      { text: "Which restaurant in Portland has the best cocktails?", category: "bar" },
      { text: "Best restaurant in Portland for vegetarians", category: "dietary" },
      { text: "Highest rated restaurant in Portland Oregon", category: "general" },
      { text: "Best restaurant with patio in Portland", category: "outdoor" },
      { text: "Top reviewed restaurant in Portland", category: "general" },
      { text: "Best restaurant in Portland for groups", category: "group dining" },
      { text: "Which Portland restaurant is best for celebrations?", category: "specialty" },
      { text: "Best restaurant in Portland for happy hour", category: "bar" },
      { text: "Best Italian restaurant in Portland", category: "cuisine" },
      { text: "Top seafood restaurant in Portland OR", category: "cuisine" },
      { text: "Best restaurant in Pearl District Portland", category: "location" },
      { text: "Which restaurant in Portland has the best reviews?", category: "general" },
      { text: "Best restaurant in Portland for anniversary dinner", category: "romantic" },
      { text: "Top rated bistro in Portland Oregon", category: "general" },
      { text: "Best restaurant in Portland with tasting menu", category: "fine dining" },
      { text: "Which Portland restaurant is best for breakfast?", category: "brunch" },
      { text: "Best restaurant in Portland for private events", category: "specialty" },
      { text: "Best restaurant in Portland with live music", category: "specialty" },
      { text: "Top-rated restaurant in Southeast Portland", category: "location" },
      { text: "Best restaurant in Portland for lunch", category: "general" },
      { text: "Which restaurant in Portland is best for gluten-free?", category: "dietary" },
      { text: "Best restaurant in Portland for wine pairing", category: "bar" },
    ],
    reportHighlight: "Date night queries jumped from 6 to 19 mentions after publishing curated tasting menu content.",
    nextSteps: [
      "Create curated experience menus (date night, celebration, tasting)",
      "Add detailed cuisine and dietary restriction content",
      "Improve Google Business Profile with updated menu photos",
      "Strengthen presence on OpenTable and Resy with rich descriptions",
      "Publish chef spotlight and sourcing stories",
    ],
  },
  {
    id: "realestate",
    label: "Real Estate Companies",
    emoji: "🏢",
    businessType: "company",
    exampleBusiness: "Cornerstone Realty",
    exampleCity: "Charlotte",
    exampleState: "NC",
    exampleWebsite: "cornerstonerealtycharlotte.com",
    competitors: [
      { name: "Queen City Properties", baseScore: 78 },
      { name: "Premier Charlotte Homes", baseScore: 65 },
      { name: "Lake Norman Realty", baseScore: 56 },
      { name: "Tarheel Property Group", baseScore: 48 },
    ],
    queries: [
      { text: "Best real estate agent in Charlotte", category: "general" },
      { text: "Top-rated realtor near me in Charlotte", category: "general" },
      { text: "Best real estate company in Charlotte NC", category: "general" },
      { text: "Best realtor for first-time home buyers Charlotte", category: "buyers" },
      { text: "Who is the best real estate agent in Charlotte?", category: "general" },
      { text: "Best realtor for selling a house in Charlotte", category: "sellers" },
      { text: "Top real estate company for luxury homes Charlotte", category: "luxury" },
      { text: "Best realtor for condos in Charlotte", category: "property type" },
      { text: "Which real estate agent in Charlotte knows Uptown best?", category: "location" },
      { text: "Best real estate company for relocations to Charlotte", category: "relocation" },
      { text: "Highest rated real estate company in Charlotte NC", category: "general" },
      { text: "Best realtor for investment properties in Charlotte", category: "investment" },
      { text: "Top reviewed real estate agent in Charlotte", category: "general" },
      { text: "Best real estate company for new construction Charlotte", category: "new construction" },
      { text: "Which Charlotte realtor is best for townhomes?", category: "property type" },
      { text: "Best real estate company for short sales Charlotte", category: "sellers" },
      { text: "Best realtor for waterfront homes near Charlotte", category: "specialty" },
      { text: "Top real estate company for property management Charlotte", category: "management" },
      { text: "Best real estate agent accepting new clients in Charlotte", category: "general" },
      { text: "Which real estate company in Charlotte has the best reviews?", category: "general" },
      { text: "Best realtor for historic homes in Charlotte", category: "specialty" },
      { text: "Top real estate agency in Charlotte North Carolina", category: "general" },
      { text: "Best real estate company for land sales Charlotte", category: "specialty" },
      { text: "Which Charlotte realtor offers the best marketing?", category: "sellers" },
      { text: "Best real estate company for commercial property Charlotte", category: "commercial" },
      { text: "Best realtor for South Charlotte neighborhoods", category: "location" },
      { text: "Top-rated real estate company in Matthews NC", category: "location" },
      { text: "Best realtor for downsizing in Charlotte", category: "sellers" },
      { text: "Which real estate agent in Charlotte is best for seniors?", category: "specialty" },
      { text: "Best real estate company for rental homes Charlotte", category: "management" },
    ],
    reportHighlight: "First-time buyer queries improved from 10 to 23 mentions after publishing neighborhood guides.",
    nextSteps: [
      "Create comprehensive neighborhood guide content for top Charlotte areas",
      "Add home valuation tool with clear landing page",
      "Publish first-time buyer resource center",
      "Improve agent profile pages with credentials and specialties",
      "Strengthen presence on Zillow and Realtor.com with optimized bios",
    ],
  },
  {
    id: "saas",
    label: "SaaS Companies",
    emoji: "💻",
    businessType: "company",
    exampleBusiness: "Flowboard",
    exampleCity: "San Francisco",
    exampleState: "CA",
    exampleWebsite: "flowboard.io",
    competitors: [
      { name: "TaskWave", baseScore: 84 },
      { name: "NexaCloud", baseScore: 71 },
      { name: "SyncStack", baseScore: 60 },
      { name: "Brightline OS", baseScore: 52 },
    ],
    queries: [
      { text: "Best project management software for small teams", category: "use case" },
      { text: "Top-rated SaaS tool for team collaboration", category: "category" },
      { text: "Best alternative to Asana for startups", category: "comparison" },
      { text: "Best workflow automation tool 2026", category: "category" },
      { text: "Who makes the best task management software?", category: "category" },
      { text: "Best project management tool for remote teams", category: "use case" },
      { text: "Top SaaS for agile project management", category: "methodology" },
      { text: "Best kanban board software for developers", category: "use case" },
      { text: "Which project management tool integrates with Slack?", category: "integration" },
      { text: "Best SaaS for time tracking and invoicing", category: "category" },
      { text: "Highest rated project management software 2026", category: "general" },
      { text: "Best Gantt chart software for project planning", category: "feature" },
      { text: "Top reviewed team productivity software", category: "category" },
      { text: "Best project management tool for agencies", category: "use case" },
      { text: "Which SaaS is best for cross-functional teams?", category: "use case" },
      { text: "Best free project management software", category: "pricing" },
      { text: "Best CRM with project management features", category: "comparison" },
      { text: "Top SaaS for resource management", category: "category" },
      { text: "Best project management tool for enterprise", category: "use case" },
      { text: "Which project management software has the best reviews?", category: "general" },
      { text: "Best project management tool for product teams", category: "use case" },
      { text: "Top rated SaaS for sprint planning", category: "methodology" },
      { text: "Best project management tool with time tracking", category: "feature" },
      { text: "Which project management SaaS offers the best API?", category: "feature" },
      { text: "Best project management tool for freelancers", category: "use case" },
      { text: "Best project management software for construction", category: "industry" },
      { text: "Top-rated SaaS for marketing teams", category: "use case" },
      { text: "Best project management tool for nonprofits", category: "industry" },
      { text: "Which SaaS is best for multi-project management?", category: "feature" },
      { text: "Best project management tool with Gantt and kanban", category: "feature" },
    ],
    reportHighlight: "Comparison queries (vs competitors) grew from 5 to 16 mentions after publishing detailed comparison pages.",
    nextSteps: [
      "Publish head-to-head comparison pages against top competitors",
      "Create use-case landing pages for each target persona",
      "Add G2 and Capterra review generation program",
      "Improve integration marketplace pages with clear documentation",
      "Build content hub around agile and remote work methodologies",
    ],
  },
  {
    id: "ecommerce",
    label: "E-commerce Brands",
    emoji: "📦",
    businessType: "brand",
    exampleBusiness: "TerraGear Outdoors",
    exampleCity: "Boulder",
    exampleState: "CO",
    exampleWebsite: "terragear.com",
    competitors: [
      { name: "WildPath Supply", baseScore: 83 },
      { name: "Basecamp Outfitters", baseScore: 70 },
      { name: "Trailhead Goods", baseScore: 58 },
      { name: "Summit Supply Co", baseScore: 49 },
    ],
    queries: [
      { text: "Best hiking backpack brands 2026", category: "product type" },
      { text: "Top-rated outdoor gear brands", category: "category" },
      { text: "Best affordable hiking backpack", category: "product type" },
      { text: "Best outdoor gear for beginners", category: "audience" },
      { text: "Who makes the best camping backpacks?", category: "product type" },
      { text: "Best hiking gear brand for women", category: "audience" },
      { text: "Top outdoor brand for sustainable gear", category: "value" },
      { text: "Best lightweight backpack for thru-hiking", category: "use case" },
      { text: "Which outdoor brand has the best warranty?", category: "value" },
      { text: "Best camping gear for car camping", category: "use case" },
      { text: "Highest rated outdoor gear brand 2026", category: "general" },
      { text: "Best budget outdoor gear brand", category: "value" },
      { text: "Top reviewed hiking gear brands", category: "category" },
      { text: "Best outdoor brand for ultralight gear", category: "feature" },
      { text: "Which outdoor brand is best for backpackers?", category: "audience" },
      { text: "Best outdoor gear for cold weather camping", category: "use case" },
      { text: "Best rain jacket brand for hiking", category: "product type" },
      { text: "Top outdoor brand for camping tents", category: "product type" },
      { text: "Best outdoor gear brand on Amazon", category: "channel" },
      { text: "Which outdoor gear brand has the best reviews?", category: "general" },
      { text: "Best hiking boots brand for beginners", category: "product type" },
      { text: "Top rated camping cookware brand", category: "product type" },
      { text: "Best outdoor brand for family camping", category: "audience" },
      { text: "Which outdoor brand offers the best value?", category: "value" },
      { text: "Best outdoor gear for desert hiking", category: "use case" },
      { text: "Best sleeping bag brand for backpacking", category: "product type" },
      { text: "Top-rated outdoor brand for durability", category: "feature" },
      { text: "Best outdoor brand for trail running gear", category: "use case" },
      { text: "Which outdoor gear brand is best for thru-hikers?", category: "audience" },
      { text: "Best outdoor gear for winter hiking", category: "use case" },
    ],
    reportHighlight: "Product category queries grew from 8 to 22 mentions after adding detailed product comparison guides.",
    nextSteps: [
      "Create head-to-head product comparison guides against competitors",
      "Add detailed product use-case content (by terrain, season, experience level)",
      "Improve product page structured data and rich snippets",
      "Build review generation program across Amazon and direct site",
      "Publish sustainability and warranty content for brand trust signals",
    ],
  },
  {
    id: "b2b",
    label: "B2B Companies",
    emoji: "💼",
    businessType: "company",
    exampleBusiness: "Meridian B2B Solutions",
    exampleCity: "Chicago",
    exampleState: "IL",
    exampleWebsite: "meridianb2b.com",
    competitors: [
      { name: "Vanta Business Group", baseScore: 79 },
      { name: "Keystone B2B", baseScore: 66 },
      { name: "Apex Commercial Services", baseScore: 57 },
      { name: "Windy City B2B", baseScore: 48 },
    ],
    queries: [
      { text: "Best B2B lead generation company", category: "service" },
      { text: "Top-rated B2B marketing agency near me", category: "service" },
      { text: "Best B2B services company in Chicago", category: "general" },
      { text: "Best B2B sales outsourcing company", category: "service" },
      { text: "Who is the best B2B consultancy in Chicago?", category: "general" },
      { text: "Best B2B company for account-based marketing", category: "service" },
      { text: "Top B2B solutions provider for mid-market companies", category: "audience" },
      { text: "Best B2B company for SaaS lead generation", category: "industry" },
      { text: "Which B2B agency in Chicago specializes in manufacturing?", category: "industry" },
      { text: "Best B2B company for outbound sales", category: "service" },
      { text: "Highest rated B2B services company", category: "general" },
      { text: "Best B2B demand generation agency", category: "service" },
      { text: "Top reviewed B2B company in Chicago", category: "general" },
      { text: "Best B2B company for enterprise sales", category: "audience" },
      { text: "Which Chicago B2B firm is best for startups?", category: "audience" },
      { text: "Best B2B company for content marketing", category: "service" },
      { text: "Best B2B telemarketing company", category: "service" },
      { text: "Top B2B company for sales enablement", category: "service" },
      { text: "Best B2B company for CRM implementation", category: "service" },
      { text: "Which B2B company has the best reviews?", category: "general" },
      { text: "Best B2B company for marketing automation", category: "service" },
      { text: "Top rated B2B consultancy in Chicago IL", category: "general" },
      { text: "Best B2B company for pipeline building", category: "service" },
      { text: "Which Chicago B2B agency offers the best ROI?", category: "general" },
      { text: "Best B2B company for LinkedIn lead gen", category: "service" },
      { text: "Best B2B company for cold email campaigns", category: "service" },
      { text: "Top-rated B2B firm in the Midwest", category: "general" },
      { text: "Best B2B company for channel sales", category: "service" },
      { text: "Which B2B company is best for professional services?", category: "industry" },
      { text: "Best B2B company for revenue operations", category: "service" },
    ],
    reportHighlight: "Lead generation service queries grew from 9 to 21 mentions after publishing industry-specific case studies.",
    nextSteps: [
      "Publish industry-specific case studies with measurable results",
      "Create service comparison pages (ABM vs outbound vs inbound)",
      "Add team credential pages with industry expertise",
      "Strengthen presence on Clutch and G2 with client reviews",
      "Build content hub around B2B sales methodology",
    ],
  },
  {
    id: "education",
    label: "Education Companies",
    emoji: "🎓",
    businessType: "company",
    exampleBusiness: "BrightPath Learning",
    exampleCity: "Boston",
    exampleState: "MA",
    exampleWebsite: "brightpathlearning.com",
    competitors: [
      { name: "ScholarPath Education", baseScore: 80 },
      { name: "LearnWell Academy", baseScore: 67 },
      { name: "NextGen Tutoring", baseScore: 56 },
      { name: "Beacon Learning Group", baseScore: 49 },
    ],
    queries: [
      { text: "Best tutoring company in Boston", category: "general" },
      { text: "Top-rated SAT prep course near me", category: "test prep" },
      { text: "Best education company in Boston MA", category: "general" },
      { text: "Best online tutoring service for high schoolers", category: "tutoring" },
      { text: "Who is the best education company in Boston?", category: "general" },
      { text: "Best tutoring for math in Boston", category: "subject" },
      { text: "Top education company for college counseling", category: "college" },
      { text: "Best ACT prep company in Boston", category: "test prep" },
      { text: "Which education company in Boston offers AP tutoring?", category: "subject" },
      { text: "Best education company for special needs tutoring", category: "specialty" },
      { text: "Highest rated education company in Boston Massachusetts", category: "general" },
      { text: "Best tutoring company for reading comprehension Boston", category: "subject" },
      { text: "Top reviewed education company in Boston", category: "general" },
      { text: "Best education company for STEM tutoring", category: "subject" },
      { text: "Which Boston education company is best for ADHD students?", category: "specialty" },
      { text: "Best education company for homework help", category: "tutoring" },
      { text: "Best college admissions consulting in Boston", category: "college" },
      { text: "Top education company for ISEE prep in Boston", category: "test prep" },
      { text: "Best education company for summer programs Boston", category: "programs" },
      { text: "Which education company in Boston has the best reviews?", category: "general" },
      { text: "Best tutoring company for writing in Boston", category: "subject" },
      { text: "Top rated learning center in Boston MA", category: "general" },
      { text: "Best education company for GRE prep", category: "test prep" },
      { text: "Which Boston tutoring service offers online sessions?", category: "tutoring" },
      { text: "Best education company for group classes Boston", category: "programs" },
      { text: "Best education company for science tutoring Boston", category: "subject" },
      { text: "Top-rated education company in Cambridge MA", category: "general" },
      { text: "Best education company for executive function coaching", category: "specialty" },
      { text: "Which education company in Boston is best for gifted students?", category: "specialty" },
      { text: "Best education company for MCAT prep Boston", category: "test prep" },
    ],
    reportHighlight: "Test prep queries grew from 7 to 19 mentions after adding score improvement guarantee content.",
    nextSteps: [
      "Create score improvement guarantee landing page with clear terms",
      "Add tutor profile pages with credentials and specialties",
      "Publish subject-specific resource pages (math, reading, science)",
      "Strengthen presence on Wyzant and Care.com with optimized profiles",
      "Build parent resource center with college admissions timeline",
    ],
  },
  {
    id: "automotive",
    label: "Automotive Businesses",
    emoji: "🚗",
    businessType: "shop",
    exampleBusiness: "Apex Auto Repair",
    exampleCity: "Houston",
    exampleState: "TX",
    exampleWebsite: "apexautohouston.com",
    competitors: [
      { name: "Bayou City Auto", baseScore: 77 },
      { name: "Reliable Car Care", baseScore: 64 },
      { name: "Houston Auto Works", baseScore: 55 },
      { name: "Space City Mechanics", baseScore: 47 },
    ],
    queries: [
      { text: "Best auto repair shop in Houston", category: "general" },
      { text: "Top-rated mechanic near me for brake repair", category: "repair" },
      { text: "Best auto repair shop in Houston TX", category: "general" },
      { text: "Affordable transmission repair Houston", category: "transmission" },
      { text: "Who is the best mechanic in Houston?", category: "general" },
      { text: "Best auto repair for AC service in Houston", category: "repair" },
      { text: "Top auto shop for oil change in Houston", category: "maintenance" },
      { text: "Best mechanic for European cars in Houston", category: "specialty" },
      { text: "Which auto repair shop in Houston is ASE certified?", category: "certification" },
      { text: "Best auto repair for check engine light Houston", category: "diagnostics" },
      { text: "Highest rated auto repair shop in Houston Texas", category: "general" },
      { text: "Best mechanic for BMW repair in Houston", category: "specialty" },
      { text: "Top reviewed auto repair shop in Houston", category: "general" },
      { text: "Best auto shop for tire alignment Houston", category: "maintenance" },
      { text: "Which Houston mechanic is best for Toyota?", category: "specialty" },
      { text: "Best auto repair for hybrid vehicles Houston", category: "specialty" },
      { text: "Best mechanic for pre-purchase inspection Houston", category: "inspection" },
      { text: "Top auto shop for battery replacement Houston", category: "maintenance" },
      { text: "Best auto repair shop accepting new customers Houston", category: "general" },
      { text: "Which auto repair shop in Houston has the best reviews?", category: "general" },
      { text: "Best mechanic for Honda repair in Houston", category: "specialty" },
      { text: "Top rated auto service in Houston Texas", category: "general" },
      { text: "Best auto shop for exhaust repair Houston", category: "repair" },
      { text: "Which Houston auto repair offers shuttle service?", category: "amenities" },
      { text: "Best auto repair for Mercedes in Houston", category: "specialty" },
      { text: "Best mechanic for electrical issues Houston", category: "diagnostics" },
      { text: "Top-rated auto repair in Spring TX", category: "general" },
      { text: "Best auto shop for state inspection Houston", category: "inspection" },
      { text: "Which mechanic in Houston is best for fleet vehicles?", category: "commercial" },
      { text: "Best auto repair for timing belt replacement Houston", category: "repair" },
    ],
    reportHighlight: "Brake repair queries climbed from 8 to 20 mentions after adding brake service FAQ content.",
    nextSteps: [
      "Create detailed service pages for top repair categories (brakes, AC, transmission)",
      "Add ASE certification and manufacturer-specific expertise content",
      "Improve Google Business Profile with service photos and hours",
      "Fix inconsistent listing data across AutoMD, RepairPal, and Yelp",
      "Publish maintenance schedule content for popular vehicle makes",
    ],
  },
];

export const INDUSTRY_MAP: Record<string, IndustryConfig> = INDUSTRIES.reduce(
  (map, ind) => ({ ...map, [ind.id]: ind }),
  {}
);

export const DEFAULT_INDUSTRY = INDUSTRIES[0];
